trigger:
  batch: false
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

resources:
  containers:
  - container: datadog-agent
    image: datadog/agent:7
    options: --health-cmd="exit 0" --health-interval=1s
    ports:
    - 8125:8125
    - 8126:8126
    env:
      DD_API_KEY: $(ddAPIKey)
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_AC_EXCLUDE: "name:datadog-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

jobs:
- job: UnitTests
  pool:
    vmImage: "Ubuntu-16.04"
  container:
    image: ruby:$(RUBY_VERSION)
    options: >-
      -l com.datadoghq.ad.logs="[{\"source\": \"Azure Pipeline\", \"service\": \"dogapi-rb\"}]"
  services:
    datadog-agent: datadog-agent
  strategy:
    matrix:
      Rb19:
        RUBY_VERSION: '1.9.3'
        TASK: spec
        BUNDLE_GEMFILE: 'Gemfile_1.9'
        BUNDLER_VERSION: 'gem install bundler -v 1.0.10'
      Rb24:
        RUBY_VERSION: '2.4'
        TASK: spec
        BUNDLE_GEMFILE: Gemfile
        BUNDLER_VERSION: ''
      Rb25:
        RUBY_VERSION: '2.5'
        TASK: spec
        BUNDLE_GEMFILE: Gemfile
        BUNDLER_VERSION: ''
      Rb26:
        RUBY_VERSION: '2.6'
        TASK: spec
        BUNDLE_GEMFILE: Gemfile
        BUNDLER_VERSION: ''
      Rb27:
        RUBY_VERSION: '2.7'
        TASK: spec
        BUNDLE_GEMFILE: Gemfile
        BUNDLER_VERSION: ''
      Lint:
        RUBY_VERSION: '2.6'
        TASK: rubocop
        BUNDLE_GEMFILE: Gemfile
        BUNDLER_VERSION: ''
  steps:
    - script: |
        $(BUNDLER_VERSION)
        bundle install --retry=3 --jobs=4
      displayName: 'bundle install'
      env:
        BUNDLE_GEMFILE: $(BUNDLE_GEMFILE)
        GEM_HOME: '~/.gem'
    - script: bundle exec rake $(TASK)
      displayName: Run $(TASK) via bundle
      env:
        BUNDLE_GEMFILE: $(BUNDLE_GEMFILE)
        GEM_HOME: '~/.gem'
        DD_AGENT_HOST: datadog-agent
        DD_ENV: ci
        DD_SERVICE: dogapi-rb
        DD_TAGS: "team:integration-tools-and-libraries,runtime:ruby-$(RUBY_VERSION),ci.job.name:$(System.JobName),matrix:$(TASK)"
        DD_TRACE_ANALYTICS_ENABLED: "true"
